### PR TITLE
3.4.4 was released and this is the update

### PR DESCRIPTION
**Pull request by jjasghar**
- Update Rabbitmq to 3.4.4

### CODE REVIEW

**Comment by cmluciano** [comment]
+1 
I just pulled this in and it works on centos and ubuntu.

**Comment by jjasghar** [comment]
Can you confirm the distro pkg for centos? That's the one that kept failing for me.

**Comment by cmluciano** [comment]
CentOS-6.5 is good
```
[vagrant@default-centos-65 ~]$ yum info rabbitmq-server
Loaded plugins: fastestmirror
Determining fastest mirrors
 * base: yum.tamu.edu
 * extras: mirror.evolvedservers.com
 * updates: mirrors.cmich.edu
erlang_solutions                                                                                                                                                          642/642
Installed Packages
Name        : rabbitmq-server
Arch        : noarch
Version     : 3.4.4
Release     : 1
Size        : 4.6 M
Repo        : installed
Summary     : The RabbitMQ server
URL         : http://www.rabbitmq.com/
License     : MPLv1.1 and MIT and ASL 2.0 and BSD
Description : RabbitMQ is an implementation of AMQP, the emerging standard for high
            : performance enterprise messaging. The RabbitMQ server is a robust and
            : scalable implementation of an AMQP broker.
```

Having problems with mirrors on centos-7.0.

**Comment by cmluciano** [comment]
Works on 7.0 now!!!
```
vagrant@default-centos-70 ~]$ yum info rabbitmq-server
Loaded plugins: fastestmirror
Determining fastest mirrors
 * base: centos.den.host-engine.com
 * epel: mirror.sfo12.us.leaseweb.net
 * extras: mirror.tzulo.com
 * updates: mirrors.cmich.edu
erlang_solutions                                                                                                                                                          642/642
Installed Packages
Name        : rabbitmq-server
Arch        : noarch
Version     : 3.4.4
Release     : 1
Size        : 4.6 M
Repo        : installed
Summary     : The RabbitMQ server
URL         : http://www.rabbitmq.com/
License     : MPLv1.1 and MIT and ASL 2.0 and BSD
Description : RabbitMQ is an implementation of AMQP, the emerging standard for high
            : performance enterprise messaging. The RabbitMQ server is a robust and
            : scalable implementation of an AMQP broker.
```

**Comment by jjasghar** [comment]
Awesome. As soon as I can I'll cut a new release

**Comment by cheeseplus** [comment]
@jjasghar asked me to give this a review. It appears the "default-use-distro-version-centos" tests are failing.

First both are broken because the case statement here
https://github.com/jjasghar/rabbitmq/blob/master/recipes/default.rb#L110
Doesn't have the same check as debian has here
https://github.com/jjasghar/rabbitmq/blob/master/recipes/default.rb#L46

Even if that is fixed, there is something more fundamentally broken
centos-7 - fails because a dep is not being met:
https://gist.github.com/0dd6485823cd585a42b2

centos6 - fails as it doesn't know what even is rabbitmq-server

My vote is to just exclude them from the suite (6 for sure, 7 for the time being)

**Comment by jjasghar** [comment]
@cheeseplus yeah the excludes are the right way to go. :+1:

**Comment by cmluciano** [comment]
Ya we had a similar discussion here #218

**Pull request merged**
