### PR TITLE
Fix warning:already initialized constant LOG_LEVEL

### PR DESCRIPTION
**Pull request by ruizink**
Hopefully this will fix some troubles with the Travis CI build.

### CODE REVIEW

**Comment by ruizink** [comment]
Yay, green!

**Comment by michaelklishin** [comment]
@ruizink thank you!

**Comment by jjasghar** [comment]
Can you rebase this please?

**Comment by ruizink** [comment]
Looks like you fixed the CI build before me, so, I'm renaming this PR. :)

**Pull request merged**
