### PR TITLE
Additional rabbit configs

### PR DESCRIPTION
**Pull request by jacyzon**
Implement additional rabbit configs using additional_rabbit_configs attribute, #181.

### CODE REVIEW

**Comment by cmluciano** [comment]
@Jacyzon Can you add a spec for this?

**Comment by Jacyzon** [comment]
@cmluciano spec added =)

**Comment by cmluciano** [comment]
Thanks @Jacyzon can you give me a use case for additional_configs that I would want to put into here. I'm trying to find some documentation.

**Comment by jacyzon** [comment]
[LDAP Plugin] (https://www.rabbitmq.com/ldap.html) as an example:

Enable both internal and ldap backend, like so

override additional_rabbit_configs attribute
```ruby
override['rabbitmq']['additional_rabbit_configs'] = {
  'auth_backends' => '[
    rabbit_auth_backend_internal,
    rabbit_auth_backend_ldap
  ]'
}
```

render following config
```
{rabbit,[{auth_backends, [rabbit_auth_backend_internal, rabbit_auth_backend_ldap]}]}
```

**Comment by cmluciano** [comment]
👍

**Pull request merged**
