### PR TITLE
*  add support for looback users

### PR DESCRIPTION
**Pull request by sethcall**
Pretty straightforward change

### CODE REVIEW

**Comment by jjasghar** [comment]
Any chance you can get a chefspec test in for this? Something like: https://github.com/jjasghar/rabbitmq/blob/master/spec/default_spec.rb#L94-L97 and making sure it shows up as expected?

**Comment by sethcall** [comment]
I have not done a chef_spec.  I'll see if I can get this going...

**Comment by jjasghar** [comment]
Yeah, i respect that. It's a good practice to have, and i'm trying to enforce it for any PRs from the travis build on.

**Comment by sethcall** [comment]
Tests are in

**Comment by michaelklishin** [comment]
:+1:

**Comment by stevecstian** [comment]
@sethcall @jjasghar @michaelklishin 

How about having `loopback_users` as array like below?

attributes/default.rb:
```
# rabbitmq.config defaults
default['rabbitmq']['default_user'] = 'guest'
default['rabbitmq']['default_pass'] = 'guest'

# List of users which are only permitted to connect to the broker via a loopback interface (i.e. localhost).
default['rabbitmq']['loopback_users'] = [ 'guest' ]
```

templates/default/rabbitmq.config.erb
```
     {default_user, <<"<%= node['rabbitmq']['default_user'] %>">>},
     {default_pass, <<"<%= node['rabbitmq']['default_pass'] %>">>},
<% if node['rabbitmq']['loopback_users'] -%>
    {loopback_users, [<%= node['rabbitmq']['loopback_users'].map{|n| "<<\"#{n}\">>"}.join(',') %>]},
<% end %>
     {heartbeat, <%= node['rabbitmq']['heartbeat'] %>}
```
You might want to test:
* attribute value is `nil`
* single loopback user
* multiple loopback users

Consider to add some descriptions for this new attribute in README.md or even metadata.rb.

**Comment by sethcall** [comment]
Yes good point. I'll make that change

**Comment by sethcall** [comment]
@stevecstian  I went with all of your suggestions; I also added a default value in the attributes/default.rb file to let people know the config is available (I almost always go there 1st when learning any cookbook).

The readme has no mention of any attributes/default.rb, so I added default_user and default_pass, along with loopback_user... (it would have been weird to have loopback_user all by itself).

**Comment by stevecstian** [comment]
@sethcall You ROCK :metal: !   
I'd give this :+1: :+1: 

I just realized that we have 2 different places to describe attributes: 
* `metadata.rb`: description, type, default, ...
* `README.rb`: usage, ...

I'm fine to have a sub-section in `README.rb` for attributes.  But I think @jjasghar can make a final call on this.

I'm OK to have `nil` as the default value of `loopback_users`.  The only reason I prefer to use `['guest']` as default value because user can easily realize we should assign an array for this attribute.  But I guess that's not really a big deal... 

@jjasghar @michaelklishin Any suggestions?

/CC @tsupertramp for similar fix in #206

**Comment by thomaspeitz** [comment]
@sethcall Yeah! Thanks!

**Comment by sethcall** [comment]
I didn't even look at metadata.rb.  I've updated it to keep in line with the other attributes. 

I think your point about specifying an array of users is smart.   I tried to address your concern in the readme, by making a specific example of specifying a user.

**Comment by stevecstian** [comment]
:+1:

**Pull request merged**
