### PR TITLE
Add more support for erlang args

### PR DESCRIPTION
**Pull request by kramvan1**

### CODE REVIEW

**Comment by kramvan1** [comment]
@cmluciano should be ready now, sorry for the CI churn

**Comment by cmluciano** [comment]
Nice, can you squash your commits to one?

**Comment by kramvan1** [comment]
Squashed down to 1 commit, @cmluciano thx.

**Comment by cmluciano** [comment]
LGTM @jjasghar

**Comment by michaelklishin** [comment]
+1 :+1:

**Comment by kramvan1** [comment]
@jjasghar  Just a follow up that I would like to see this merged and a new version cut as it's critical to support advanced HA openstack environments.

**Pull request merged**
