### PR TITLE
Add support for Stomp configuration

### PR DESCRIPTION
**Pull request by davent**

### CODE REVIEW

**Comment by cmluciano** [comment]
@davent Do you have any interest in rebasing and adding a spec for this?

**Comment by davent** [comment]
Yes sure

**Comment by cmluciano** [comment]
@davent can you correct the foodcritic errors and also add a spec for this?

**Comment by jjasghar** [comment]
@davent can you fix the travis failures? I'd like to merge this. :)

**Comment by jjasghar** [comment]
@davent any chance to fix the travis failures?

**Comment by jjasghar** [comment]
I'm going to close this due to no activity.

**Pull request closed without merging**
