### PR TITLE
Enable chef setting for tcp_listen linger option

### PR DESCRIPTION
**Pull request by mgosalia**

### CODE REVIEW

**Comment by mgosalia** [comment]
@jjasghar could you please review this ?
Reference - https://www.rabbitmq.com/networking.html
grep for "linger".

**Comment by jjasghar** [comment]
I'll take a look at this, and do some research on this.

@michaelklishin any thoughts on this option? This is the first i've heard of it.

**Comment by mgosalia** [comment]
@michaelklishin fyi...I had sent out an email to openstack-operators mailing list as well. 
Here is the email - http://lists.openstack.org/pipermail/openstack-operators/2015-November/008878.html

**Comment by mgosalia** [comment]
Thanks @jjasghar

**Comment by michaelklishin** [comment]
Socket lingering is primarily useful to clients but I have no objections to this. Keep in mind that as of `3.6.0` we will be using a TCP acceptor library called Ranch, which has sensible defaults for most, and is fairly strict about rejecting options it doesn't support (in general, the options are nearly identical to `gen_tcp`, though).

**Comment by mgosalia** [comment]
@michaelklishin  do we know for sure that linger {true, 0} is always the default setting in rabbitmq config ?
This documentation [1] does say so.

[1] - https://www.rabbitmq.com/networking.html

**Comment by michaelklishin** [comment]
@mgosalia see for yourself:

 * [in master](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit.app.src#L61)
 * [in stable](https://github.com/rabbitmq/rabbitmq-server/blob/stable/ebin/rabbit_app.in#L63)

**Comment by mgosalia** [comment]
Thanks @michaelklishin. 
@jjasghar  is it good to go ? This change will help us at Yahoo to configure the value.

**Comment by jjasghar** [comment]
I'm going to run this through our testing today. Any chance you can create an integration/unit test for this? I really don't like adding things to this cookbook without test coverage.

**Comment by mgosalia** [comment]
@jjasghar sure...will add unit tests. I tried to look for existing tests related to rabbitmq config and did not find any. So, had skipped it. Let me dig more.

**Comment by jjasghar** [comment]
Sounds good, just Unit tests are probably fine. When you get them added I'll go through my release process and get this pushed out.

**Comment by mgosalia** [comment]
@jjasghar have updated the change with unit tests. Could you please review it again ? Thanks.

**Comment by jjasghar** [comment]
Awesome, thanks. I'll run some final tests and push out a new version ASAP.

**Pull request merged**
