### PR TITLE
Adds some LWRPs for managing exchanges

### PR DESCRIPTION
**Pull request by hufman**
Uses the REST api to add and remove Exchanges and Exchange Bindings.

### CODE REVIEW

**Comment by dblessing** [comment]
@hufman Is there anything holding this up?

**Comment by hufman** [comment]
I'm sorry, I haven't had time to work on this since then, my job has called me away to other things.

**Comment by cmluciano** [comment]
I can try to clean this up if we think it is still a good approach. cc @michaelklishin @jjasghar

**Comment by cmluciano** [comment]
Closing due to inactivity, opened issue [#251](https://github.com/jjasghar/rabbitmq/issues/251) as a placeholder to refactor this with the https://github.com/ruby-amqp/rabbitmq_http_api_client

**Pull request closed without merging**
