### PR TITLE
Add more chefspec tests

### PR DESCRIPTION
**Pull request by wenchma**
Add some missing spec tests to cover more chef resources,
but it reports some same untouched resources repeatedly
for many times.

Fixes issue #190

### CODE REVIEW

**Comment by jjasghar** [comment]
I think this is in reference to something like this: https://github.com/jjasghar/rabbitmq/pull/168/files#diff-55bf87238c9b8af164c5133a60721f12R169

**Comment by jjasghar** [comment]
@wenchma I tried fixing these errors, couldnt fix it :(.

Can you rip out those tests, so we can get this merged in?

**Comment by wenchma** [comment]
updated the PR for spec tests

**Comment by wenchma** [comment]
~/rabbitmq$ rspec spec/
....................................

Finished in 1 minute 28.43 seconds (files took 4.51 seconds to load)
36 examples, 0 failures

ChefSpec Coverage report generated...

  Total Resources:   23
  Touched Resources: 23
  Touch Coverage:    100.0%

You are awesome and so is your test coverage! Have a fantastic day!

**Comment by wenchma** [comment]
@jjasghar  success to run rspec on my local env, but the travis CI build failed,  it confused me.

**Comment by jjasghar** [comment]
Man, i try it on my local box, checking out your branch, and i get errors all over the place.

are you running this on a box _with_ rabbitmq installed on it? I'm not and i'm seeing errors.

I'm gonna close the issue #190 so we have the conversation in one place.

**Comment by jjasghar** [comment]
@wenchma can you rebase this guy and see if travis'll pass now? I think i've fixed things upstream.

**Comment by wenchma** [comment]
@jjasghar Ok. I will rebase it and update the PR

**Comment by wenchma** [comment]
have updated the PR, and the coverage result:
Finished in 1 minute 28.65 seconds (files took 4.43 seconds to load)
38 examples, 0 failures

ChefSpec Coverage report generated...

  Total Resources:   23
  Touched Resources: 23
  Touch Coverage:    100.0%

You are awesome and so is your test coverage! Have a fantastic day!

**Pull request merged**
