### PR TITLE
Use init if job_control uses init.

### PR DESCRIPTION
**Pull request by rogerhu**
Ubuntu 15.04 machines will otherwise try to use SystemD.

### CODE REVIEW

**Comment by jjasghar** [comment]
This is awesome thank you. But technically speaking yet we don't support 15.04. I'll put it on the todo list, but I have more things to happen before i can merge this.

**Comment by majormoses** [comment]
sounds good to me regardless of ubuntu 15.04 support.

**Comment by rogerhu** [comment]
15.10 is out too =)

**Comment by majormoses** [comment]
Indeed, I mean that even if we only "officially" support ubuntu LTS versions (at least non eol versions) if someone is going to put forth effort to expand functionality then we should certainly allow it if its sane. Also this will probably make it easier to support 16.04 which will release in april I believe. =)

@jjasghar +1

**Pull request merged**
