### PR TITLE
Support rabbitmq_user with multiple vhosts.

### LINKED ISSUE #278: Feature Request: Support rabbitmq_user with multiple vhosts.
RabbitMQ has the ability to give a single user access to more than one vhost.  It would be nice to be able to take advantage of this from a recipe.

in our case, it is for a master admin user that has admin access to all vhosts, such as:
```ruby
# Create a user for administration of all vhosts
rabbitmq_user "overall_admin" do
  vhost ["/", "foo", "bar"]
  password overall_admin_password
  permissions ".* .* .*"
  tag "administrator"
  action [:add, :set_permissions, :set_tags]
end
```

### PR DESCRIPTION
**Pull request by jemc**
Resolves #278.

### CODE REVIEW

**Comment by jemc** [comment]
@jjasghar 
I fixed the Rubocop offense seen on Travis-CI.

I see you added the tag `Need a spec`.  However, as far as I can tell there are no specs at all for the `rabbitmq_user` resource/provider.  Am I missing something?

**Comment by trotttrotttrott** [comment]
:+1:

**Comment by inkel** [comment]
:+1: this is really useful

**Comment by tas50** [comment]
:+1: It would be great to get this one merged and released.

**Comment by jjasghar** [comment]
I'm planning on releasing another version of the rabbitmq cookbook this by end of week

**Pull request merged**
