### PR TITLE
Add ability to set loopback_users (only localhost access)

### PR DESCRIPTION
**Pull request by tsupertramp**
Please give me feedback :)

I was unsure if this is something which should be set through the user lwrp but it
is not really handy to test it. (The rabbitmqctl has no command to verify the
loopback_users) - So I decided to make it this way.

Greetings Thomas

### CODE REVIEW

**Comment by stevecstian** [comment]
@tsupertramp 
How about have something like below?

attributes/default.rb:
```
# rabbitmq.config defaults
default['rabbitmq']['default_user'] = 'guest'
default['rabbitmq']['default_pass'] = 'guest'

# List of users which are only permitted to connect to the broker via a loopback interface (i.e. localhost).
default['rabbitmq']['loopback_users'] = [ 'guest' ]
```

templates/default/rabbitmq.config.erb
```
     {default_user, <<"<%= node['rabbitmq']['default_user'] %>">>},
     {default_pass, <<"<%= node['rabbitmq']['default_pass'] %>">>},
<% if node['rabbitmq']['loopback_users'] -%>
    {loopback_users, [<%= node['rabbitmq']['loopback_users'].map{|n| "<<\"#{n}\">>"}.join(',') %>]},
<% end %>
     {heartbeat, <%= node['rabbitmq']['heartbeat'] %>}
```
You might want to test:
* attribute value is `nil`
* single loopback user
* multiple loopback users

Consider to add some descriptions for this new attribute in README.md or even metadata.rb.

**Comment by jjasghar** [comment]
@tsupertramp looks like you got a travis failure too :)

**Comment by tsupertramp** [comment]
Thanks for your feedback :)
I will prepare a new Pull Request until Saturday.
Have a nice evening guys!

**Comment by tsupertramp** [comment]
Having Problems with chefspec - Seem to be a problem with gem versions - Explosion of my time box so i will continue to do it tomorrow.

**Comment by jjasghar** [comment]
test/cookbooks/rabbitmq_test/files/default/tests/minitest/cook-2151-3489_test.rb:36:1: C: Trailing whitespace detected.

**Comment by cmluciano** [comment]
I think this can be closed as a dup of [PR#212](https://github.com/jjasghar/rabbitmq/pull/212/files)

**Comment by jjasghar** [comment]
Closed due to #212

**Pull request closed without merging**
