### PR TITLE
Add version_release attribute

### PR DESCRIPTION
**Pull request by reneklacan**
Hi,

got following error when trying to use this cookbook

```
  * remote_file[/var/chef/cache/rabbitmq-server_3.5.5-1_all.deb] action create_if_missing[2015-10-12T11:43:07+00:00] WARN: remote_file[/var/chef/cache/rabbitmq-server_3.5.5-1_all.deb] cannot be downloaded from https://www.rabbitmq.com/releases/rabbitmq-server/v3.5.5/rabbitmq-server_3.5.5-1_all.deb: 404 "Not Found"


    ================================================================================
    Error executing action `create_if_missing` on resource 'remote_file[/var/chef/cache/rabbitmq-server_3.5.5-1_all.deb]'
    ================================================================================
```

Problem is that http://www.rabbitmq.com/releases/rabbitmq-server/v3.5.5/rabbitmq-server_3.5.5-1_all.deb is no longer accessible.

This PR adds `default['rabbitmq']['version_release']` attribute with current release.

Tested and works.

### CODE REVIEW

**Comment by michaelklishin** [comment]
This is a good idea, thank you @reneklacan. However, I'd recommend merging https://github.com/jjasghar/rabbitmq/pull/315 first and updating this PR's default value to be `1` again.

@jjasghar what do you think of https://github.com/jjasghar/rabbitmq/pull/315?

**Comment by reneklacan** [comment]
@michaelklishin makes sense :)

**Comment by jjasghar** [comment]
Oops, I thought I fixed this. 

I'll get back on it today and release.

**Comment by michaelklishin** [comment]
@reneklacan now that #15 is fixed, can we change version release to be `1`?

**Comment by michaelklishin** [comment]
@jjasghar thank you!

**Comment by reneklacan** [comment]
sure, I will change it back to 1 and fix tests ...

**Comment by jjasghar** [comment]
Please resolve the conflicts :D and see if this is still valid.

**Comment by jjasghar** [comment]
Closing due to no activity.

**Pull request closed without merging**
