### PR TITLE
Fix user_has_tag? issue when name and tag are the same

### PR DESCRIPTION
**Pull request by shunwen**
When passing a user with name "management" and tag "management", the tag won't be created because in `user_has_tag?` method the tag is considered to be existed. I think it'd be easier only run `rabbitmqctl -q list_user management` as command, and parse the result with ruby regex function like:

    cmd.run_command
    user_list = cmd.stdout # => "management\t[management test]"
    tags = user_list.match(/^#{name}\s+\[(.+*)\]/)[1].split # => ["management", "test"]

### CODE REVIEW

**Comment by tas50** [comment]
This bug is burning me right now with my monitoring user that needs the monitoring tag.  It would be really great to get this merged and released.

**Comment by jjasghar** [comment]
I'm planning on releasing another version of the rabbitmq cookbook this by end of week

**Comment by tas50** [comment]
@jjasghar Any update on getting a release out with this fix?

**Comment by jjasghar** [comment]
Ideally in the next 24 hours. $DAYJOB resposibities have been taking priorities. But I blocked off my whole afternoon to get the released.

**Pull request merged**
