### PR TITLE
fix hardcoded --ram node type for cluster join

### PR DESCRIPTION
**Pull request by scalp42**
cc @michaelklishin @jjasghar 

Tested and working:

```
[2015-12-16T01:26:23+00:00] INFO: Processing rabbitmq_cluster[[{"name":"rabbit@ec2-54-201-251-170.us-west-2.compute.amazonaws.com","type":"disc"}]] action join (gz-rabbitmq::join line 5)
[2015-12-16T01:26:23+00:00] INFO: [rabbitmq_cluster] Action join ...
[2015-12-16T01:26:24+00:00] INFO: DOUDOU => rabbit@ec2-54-201-251-170.us-west-2.compute.amazonaws.com
[2015-12-16T01:26:25+00:00] INFO: [rabbitmq_cluster] Clustering node 'rabbit@ec2-54-200-235-67.us-west-2.compute.amazonaws.com' with 'rabbit@ec2-54-201-251-170.us-west-2.compute.amazonaws.com' ...

[2015-12-16T01:26:26+00:00] INFO: [rabbitmq_cluster] Node rabbit@ec2-54-200-235-67.us-west-2.compute.amazonaws.com joined in rabbit@ec2-54-201-251-170.us-west-2.compute.amazonaws.com with type disc
[2015-12-16T01:26:26+00:00] INFO: [{nodes,[{disc,['rabbit@ec2-54-200-235-67.us-west-2.compute.amazonaws.com','rabbit@ec2-54-201-251-170.us-west-2.compute.amazonaws.com']}]},{running_nodes,['rabbit@ec2-54-201-251-170.us-west-2.compute.amazonaws.com','rabbit@ec2-54-200-235-67.us-west-2.compute.amazonaws.com']},{cluster_name,<<"rabbit@ip-10-52-42-243.us-west-2.compute.internal">>},{partitions,[]}]

root@rabbitmq-i-fef72824 ~ # rabbitmqctl cluster_status
Cluster status of node 'rabbit@ec2-54-200-235-67.us-west-2.compute.amazonaws.com' ...
[{nodes,[{disc,['rabbit@ec2-54-200-235-67.us-west-2.compute.amazonaws.com',
                'rabbit@ec2-54-201-251-170.us-west-2.compute.amazonaws.com']}]},
 {running_nodes,['rabbit@ec2-54-201-251-170.us-west-2.compute.amazonaws.com',
                 'rabbit@ec2-54-200-235-67.us-west-2.compute.amazonaws.com']},
 {cluster_name,<<"rabbit@ip-10-52-42-243.us-west-2.compute.internal">>},
 {partitions,[]}]
```

### CODE REVIEW

**Comment by michaelklishin** [comment]
Default node type should definitely not be RAM. There is no reason to use RAM nodes for 95% of the workloads.

**Comment by scalp42** [comment]
Any chance we can merge it @michaelklishin ? The failing check is related to the if condition related to the node type passed.

**Comment by jjasghar** [comment]
@scalp42 I havent had a chance to look into this yet. It's on my TODO and when i have some time i'll be visiting this.

Though i do trust @michaelklishin's opinion ;)

**Comment by jjasghar** [comment]
Can you add a skip for the travis failure too?

**Comment by scalp42** [comment]
@jjasghar passing now.

**Comment by scalp42** [comment]
@michaelklishin @jjasghar we should really merge this in, this is literally hardcoded right now.

**Comment by jjasghar** [comment]
Yep!

I just need to set up another release. It takes a bit of time so I have to schedule it.

**Pull request merged**
