### PR TITLE
Upgrade to -3_all.deb

### PR DESCRIPTION
**Pull request by jdrago999**
Because 404 error.

### CODE REVIEW

**Comment by jdrago999** [comment]
Fixes #311

**Comment by jjasghar** [comment]
Nice catch, thanks. I'll update and push the change.

**Comment by michaelklishin** [comment]
`3.5.6` is already out, supports Erlang 18.1 :)

**Comment by jjasghar** [comment]
Welp! That's another release.

**Comment by michaelklishin** [comment]
@jjasghar see my comment to #311. I think that change needs to be reverted (for `3.5.6` and in general).

**Pull request merged**
