### PR TITLE
Remove the extra curly braces for format_ssl_ciphers

### PR DESCRIPTION
**Pull request by wenchma**
Fixes issue #259

### CODE REVIEW

**Comment by kramvan1** [comment]
:+1:   Looks like my first attempt on this was a reading to much from the doc and other types of format are  easier to use.

**Comment by wenchma** [comment]
@jjasghar  any thought about this PR? I think it can be ready to merge, agree/disagree?
thanks.

**Comment by kramvan1** [comment]
Would really like to see this one in the Supermarket...any ETA on next cut?

**Comment by kramvan1** [comment]
Any ETA on next rabbitmq cut for supermarket, seems like we have a few good patches ready to go now.

**Comment by wenchma** [comment]
@jjasghar any idea ? would we ready to move on ?

**Comment by jjasghar** [comment]
I'll look a release early next week. (June 15 or 16)

**Pull request merged**
